### ISSUE TITLE
need C_ARRAY_LENGTH

### ISSUE THREAD

**Issue by bulk88** [mhx/Devel-PPPort#16]
C_ARRAY_LENGTH needs to be added from http://perl5.git.perl.org/perl.git/commitdiff/622913ab81739f4a9419ed541a122ff2495c8ab1 which was added in blead upto 5.9.0 release. Its partner C_ARRAY_END from http://perl5.git.perl.org/perl.git/commitdiff/cd431fdedf8dec69c65efa7edc1d60005800919a (5.13.1- 5.13.2) should be added too. This request is specifically since I found NYTProf is using C_ARRAY_LENGTH for some reason (Nicholas Clark seems to have added usage of it to NYTProf).

**Comment by wolfsage** [comment]
Should go out with 3.33 soon.

**Comment by wolfsage** [comment]
Thanks
