### ISSUE TITLE
[PATCHES] reduce compiler warnings and stderr noise

### ISSUE THREAD

**Issue by iabyn** [mhx/Devel-PPPort#17]
Dear maintainer of a dual-lived CPAN distribution: I'm currently attempting
to get bleadperl to be warnings-clean; i.e. where
    (./Configure && make) 2>errs
leaves no lines in 'errs'. Recently bleadperl made the -W options passed
to the C compiler more fascist, and in addition we're trying to get blead
to compile and run cleanly under clang's -fsanitize=undefined option.  Due
to that and other reasons, bleadperl's build is currently very noisy.

I've created two patches on the davem/cpan-warn branch in the perl
repository,
http://perl5.git.perl.org/perl.git/shortlog/refs/heads/davem/cpan-warn,

    9d6cda0 Devel::PPPort: silence some build warnings
    6f806d3 Devel::PPPort: fix a couple of compiler warns

that reduce the noise of your distribution when built as part of
bleadperl.

It would be great if they could make it into a new release of your
distribution in time for incorporation into perl-5.22.0. Our
timetable is:

  2015-01-20  5.21.8          Contentious changes freeze
  2015-02-20  5.21.9          User-visible changes freeze
  2015-03-20  5.21.10         Full code freeze
  2015-05-20  5.22.0          Stable release!

so for example if a new release of your distribution included contentious
features, then it would need to be merged into blead *prior* to the 20th
of Jan.

There is some residual noise which my patches don't silence:

    parts/inc/cop provides caller_cx, which is still marked todo for 5.13.5
    parts/inc/magic provides HEf_SVKEY, which is still marked todo for 5.004
    parts/inc/misc provides HeUTF8, which is still marked todo for 5.10.1
    parts/inc/misc provides isASCII, which is still marked todo for 5.6.0
    parts/inc/misc provides isCNTRL, which is still marked todo for 5.6.0
    parts/inc/magic provides mg_findext, which is still marked todo for 5.13.8
    parts/inc/variables provides PL_parser, which is still marked todo for 5.9.5
    parts/inc/magic provides sv_unmagicext, which is still marked todo for 5.13.8
    parts/inc/cop provides caller_cx, which is still marked todo for 5.13.5
    parts/inc/magic provides HEf_SVKEY, which is still marked todo for 5.004
    parts/inc/misc provides HeUTF8, which is still marked todo for 5.10.1
    parts/inc/misc provides isASCII, which is still marked todo for 5.6.0
    parts/inc/misc provides isCNTRL, which is still marked todo for 5.6.0
    parts/inc/magic provides mg_findext, which is still marked todo for 5.13.8
    parts/inc/variables provides PL_parser, which is still marked todo for 5.9.5
    parts/inc/magic provides sv_unmagicext, which is still marked todo for 5.13.8

I don't know whether these are spurious warnings which should be
silenced, or are notes which should appear on stdout instead, or that
indicate issue(s) which need fixing.

Thanks,

Dave M.

**Comment by wolfsage** [comment]
Thanks Dave, I saw those patches go by in perl5 git recently, I appreciate you throwing them here.

I'm the RM for Perl this month, so I'll make sure these make it in before 5.20 provided all testing goes smoothly.

Cheers,

-- Matthew Horsfall (alh)

**Comment by iabyn** [comment]
On Wed, Jan 07, 2015 at 06:50:40PM -0800, Matthew Horsfall (alh) wrote:
> As to the todo warnings...I need to regen the todo files but there's
> some breakage in the tooling around that that I haven't solved yet. Is
> this something we can live with for now or should we get those quieted?
> They are more or less informational as I understand it and probably
> (maybe?) harmless. 

Well, if they don't indicate an error that needs fixing, I'd suggest
the messages get sent to stdout rather than stderr.

That way when blead is built, we know that the only things on stderr
are things we need to fix.


-- 
"But Sidley Park is already a picture, and a most amiable picture too.
The slopes are green and gentle. The trees are companionably grouped at
intervals that show them to advantage. The rill is a serpentine ribbon
unwound from the lake peaceably contained by meadows on which the right
amount of sheep are tastefully arranged." -- Lady Croom, "Arcadia"

**Comment by mhx** [comment]
The messages actually indicate an inconsistency in the data D::PPP
is using internally, so IMO it's worth a warning. Inconsistent data might
lead to erroneous information being displayed and maybe even worse
behaviour that I've forgotten about :)

In any case, I've just committed an update that should align the data
with the implementation and get rid of the warnings, so this should be
fixed with the next release.

**Comment by wolfsage** [comment]
And this has been released as 3.26, with mhx's fixes in 3.27 (and another nit fix in 3.28)
