### ISSUE TITLE
Coverity finding: possible NULL deref

### ISSUE THREAD

**Issue by jhi** [mhx/Devel-PPPort#25]
Since hv_iternext can return NULL, assert(ent) is needed before the mXPUSHp.

23. var_assigned: Assigning: ent = null return value from Perl_hv_iternext_flags.
1193                ent = hv_iternext(hash);
    	24. Condition my_perl->Istack_max - sp < 1L /* (ssize_t)1 */, taking true branch
    	25. Condition (my_perl->Istack_max - sp < 1L /* (ssize_t)1 */) ? 1 /* (bool)1 */ : 0 /* (bool)0 */, taking true branch
    	
CID 104801 (#1 of 1): Dereference null return value (NULL_RETURNS)
26. dereference: Dereferencing a null pointer ent.
1194                mXPUSHp((HeUTF8(ent) == 0 ? "norm" : "utf8"), 4);

**Comment by wolfsage** [comment]
Should go out in 3.33 soon.

**Comment by wolfsage** [comment]
Thanks!
