### ISSUE TITLE
[PATCH] fix compiler warnings

### ISSUE THREAD

**Issue by iabyn** [mhx/Devel-PPPort#30]
PPP kicks up some warnings on blead with the right compiler combo:

    ../../pp.h:477:68: warning: cast from pointer to integer of different size
    [-Wpointer-to-int-cast]
        #define mXPUSHi(i) STMT_START { EXTEND(sp,1);

This diff fixes it (IFAIKT):

--- a/cpan/Devel-PPPort/parts/inc/variables
+++ b/cpan/Devel-PPPort/parts/inc/variables
@@ -222,7 +222,7 @@ extern U32 get_PL_signals_3(void);
 int no_dummy_parser_vars(int);
 int dummy_parser_warning(void);
 
-#define ppp_TESTVAR(var)          STMT_START { mXPUSHi(&var); count++; } STMT_END
+#define ppp_TESTVAR(var)          STMT_START { mXPUSHi(PTR2IV(&var)); count++; } STMT_END
 
 #define ppp_PARSERVAR(type, var)  STMT_START {                   \
                                     type volatile my_ ## var;    \

**Comment by wolfsage** [comment]
This seems okay, but adds 24 warnings to 5.003/5.004 perls. If these warnings are harmless, I'm okay applying it.
````
In file included from RealPPPort.c:156:0:
RealPPPort.c: In function ‘XS_Devel__PPPort_ptrtests’:
ppport.h:4222:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #  define PTR2nat(p)                     (PTRV)(p)
                                          ^
RealPPPort.c:2054:27: note: in expansion of macro ‘PTR2nat’
                 RETVAL += PTR2nat(p) != 0       ?  1 : 0;
                           ^
ppport.h:4210:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #    define INT2PTR(any,d)        (any)(PTRV)(d)
                                        ^
ppport.h:4218:27: note: in expansion of macro ‘INT2PTR’
 #    define PTR2ul(p)     INT2PTR(unsigned long,p)
                           ^
RealPPPort.c:2055:27: note: in expansion of macro ‘PTR2ul’
                 RETVAL += PTR2ul(p) != 0UL      ?  2 : 0;
                           ^
ppport.h:4210:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #    define INT2PTR(any,d)        (any)(PTRV)(d)
                                        ^
ppport.h:4234:42: note: in expansion of macro ‘INT2PTR’
 #  define PTR2UV(p)                      INT2PTR(UV,p)
                                          ^
RealPPPort.c:2056:27: note: in expansion of macro ‘PTR2UV’
                 RETVAL += PTR2UV(p) != (UV) 0   ?  4 : 0;
                           ^
ppport.h:4210:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #    define INT2PTR(any,d)        (any)(PTRV)(d)
                                        ^
ppport.h:4230:42: note: in expansion of macro ‘INT2PTR’
 #  define PTR2IV(p)                      INT2PTR(IV,p)
                                          ^
RealPPPort.c:2057:27: note: in expansion of macro ‘PTR2IV’
                 RETVAL += PTR2IV(p) != (IV) 0   ?  8 : 0;
                           ^
ppport.h:4222:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #  define PTR2nat(p)                     (PTRV)(p)
                                          ^
ppport.h:4226:47: note: in expansion of macro ‘PTR2nat’
 #  define NUM2PTR(any,d)                 (any)PTR2nat(d)
                                               ^
ppport.h:4238:42: note: in expansion of macro ‘NUM2PTR’
 #  define PTR2NV(p)                      NUM2PTR(NV,p)
                                          ^
RealPPPort.c:2058:27: note: in expansion of macro ‘PTR2NV’
                 RETVAL += PTR2NV(p) != (NV) 0   ? 16 : 0;
                           ^
````

**Comment by iabyn** [comment]
On Fri, Mar 18, 2016 at 08:52:10AM -0700, Matthew Horsfall (alh) wrote:
> This seems okay, but adds 24 warnings to 5.003/5.004 perls. If these warnings are harmless, I'm okay applying it.
> ````
> In file included from RealPPPort.c:156:0:
> RealPPPort.c: In function ‘XS_Devel__PPPort_ptrtests’:
> ppport.h:4222:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]

Can you give me the 'perl -V' output of a perl build this produces these
errors.

-- 
It's not that I'm afraid to die, I just don't want to be there when it
happens.
    -- Woody Allen

**Comment by wolfsage** [comment]
````
mhorsfall@dory:~/Devel-PPPort$ /home/mhorsfall/dpppperls/default/perl-5.003/bin/perl5.003 -V
Summary of my perl5 (5.0 patchlevel 3 subversion 0) configuration:
  Platform:
    osname=linux, osver=3.8.0-29-generic, archname=x86_64-linux
    uname='linux dory 3.8.0-29-generic #42~precise1-ubuntu smp wed aug 14 16:19:23 utc 2013 x86_64 x86_64 x86_64 gnulinux '
    hint=previous, useposix=true, d_sigaction=define
  Compiler:
    cc='cc', optimize='-O2', gccversion=4.6.3
    cppflags='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    ccflags ='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    stdchar='char', d_stdstdio=, usevfork=false
    voidflags=15, castflags=0, d_casti32=define, d_castneg=define
    intsize=4, alignbytes=8, usemymalloc=n, randbits=31
  Linker and Libraries:
    ld='cc', ldflags =''
    libpth=/lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib /lib64
    libs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6, so=so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared'

@INC: /home/mhorsfall/dpppperls/default/perl-5.003/lib/x86_64-linux/5.003 /home/mhorsfall/dpppperls/default/perl-5.003/lib /home/mhorsfall/dpppperls/default/perl-5.003/lib/site_perl/x86_64-linux /home/mhorsfall/dpppperls/default/perl-5.003/lib/site_perl .
````

**Comment by iabyn** [comment]
On Fri, Mar 18, 2016 at 02:19:27PM -0700, Matthew Horsfall (alh) wrote:
>     uname='linux dory 3.8.0-29-generic #42~precise1-ubuntu smp wed aug 14 16:19:23 utc 2013 x86_64 x86_64 x86_64 gnulinux '
>     intsize=4, alignbytes=8, usemymalloc=n, randbits=31

Then I'm a bit puzzled. That cast should be casting a pointer to an IV,
which on all perl builds since 1996 is supposed to be big enough to hold
a pointer type. However, The output of 'perl -V' back in 5.00x is a bit
sparse, so in particular I don't know what type/size an IV and a pointer
are in your build. I'd expect a pointer to be 64-bit, an IV to be the
same, but the warning implies otherwise.

Are you in a position to take the cc command line which generates that
warning, then replace the -o or -c with -E and direct the output to a
tmp file, which should contain all the source with macros expanded?

Then look at how the mXPUSHi() macros have been expanded, and what IV is
typedefed to etc?

-- 
My Dad used to say 'always fight fire with fire', which is probably why
he got thrown out of the fire brigade.

**Comment by wolfsage** [comment]
Sorry, not entirely sure what I'd be looking for there. However, I did find this out...

In 5.004 and earlier, this doesn't exist in handy.h:
````
handy.h:   	PTRSIZE == sizeof(void *)
````

Nor does PTRSIZE or IVSIZE.

parts/inc/misc does this:
````
#ifndef INT2PTR
#  if (IVSIZE == PTRSIZE) && (UVSIZE == PTRSIZE)
#    define PTRV                  UV
#    define INT2PTR(any,d)        (any)(d)
#  else
#    if PTRSIZE == LONGSIZE
#      define PTRV                unsigned long
#    else
#      define PTRV                unsigned
#    endif
#    define INT2PTR(any,d)        (any)(PTRV)(d)
#  endif
# endif
````

So I think INT2PTR (which was copied from a much newer perl) just doesn't have the info it needs to figure out how it should behave.

If I do this instead of the INT2PTR block:
````
#  define PTRV UV
#  define INT2PTR(any,d) (any)(d)

````

Everything is happy.

**Comment by iabyn** [comment]
On Sat, Mar 19, 2016 at 01:53:12PM -0700, Matthew Horsfall (alh) wrote:
> Sorry, not entirely sure what I'd be looking for there. However, I did find this out...
> 
> In 5.004 and earlier, this doesn't exist in handy.h:
> ````
> handy.h:   	PTRSIZE == sizeof(void *)

Then perhaps add above the "#ifndef INT2PTR" block,

#ifndef PTRSIZE
    #define PTRSIZE sizeof(void *)
#endif
#ifndef IVSIZE
    #define IVSIZE sizeof(IV)
#endif
#ifndef UVSIZE
    #define UVSIZE sizeof(UV)
#endif

etc?

-- 
Counsellor Troi states something other than the blindingly obvious.
    -- Things That Never Happen in "Star Trek" #16

**Comment by wolfsage** [comment]
I was apparently not paying much attention when I responded last.

This is from a comment:  handy.h: PTRSIZE == sizeof(void *)

The actual PTRSIZE is figured out by Configure, and set in config.h; using sizeof() doesn't work because PTRSIZE is used in other macros.

Instead, I'm just going to skip the change on 5.004 and below.

**Comment by wolfsage** [comment]
Should go out in 3.33 soon, thanks
