### ISSUE TITLE
Use of gcc specific __attribute__ causes failures on Windows

### ISSUE THREAD

**Issue by nanis** [mhx/Devel-PPPort#36]
[Sample test report][1] on Vista with MSVS 2010. Just verified on Windows 10 with MSVS 2013.

[1]: http://www.cpantesters.org/cpan/report/e887bcb3-6c0c-1014-8ef6-97e2b3c557e2

**Comment by wolfsage** [comment]
Will try to fix Friday, thanks

**Comment by nanis** [comment]
Thank you very much.

**Comment by wolfsage** [comment]
Release-3.34 just released, should fix it hopefully. Sorry for the delay.

**Comment by wolfsage** [comment]
https://github.com/mhx/Devel-PPPort/commit/b4e5f51c78d82832d379a52b227631af85e4dad6

**Comment by wolfsage** [comment]
@nanis  Can you confirm if this fixed it for you?

**Comment by nanis** [comment]
I'll check it in a couple of hours. Thank you.

**Comment by wolfsage** [comment]
Thank you!
