### ISSUE TITLE
PPPort_pm.PL giving warnings in blead

### ISSUE THREAD

**Issue by iabyn** [mhx/Devel-PPPort#38]
Since 3.35 was just pulled into blead, this has been appearing on STDERR:

magic: PERL_MAGIC_qr already provided by misc
magic: PERL_MAGIC_qr already provided by misc

**Comment by wolfsage** [comment]
Drat. I'm terribly sorry I missed this. Will try to fix this up soon.

**Comment by mhx** [comment]
I've got a local fix and will push to the repo in a bit.

**Comment by mhx** [comment]
Fixed by 7c42daaaee37045157b7794c6c9c73e378d0a3e7
